# Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.

x = int(input("digite um número inteiro:"))
print('-' * 15)
print(f"{x} X {1:2} = {x}")
print(f"{x} X {2:2} = {x*2}")
print(f"{x} X {3:2} = {x*3}")
print(f"{x} X {4:2} = {x*4}")
print(f"{x} X {5:2} = {x*5}")
print(f"{x} X {6:2} = {x*6}")
print(f"{x} X {7:2} = {x*7}")
print(f"{x} X {8:2} = {x*8}")
print(f"{x} X {9:2} = {x*9}")
print(f"{x} X 10 = {x*10}")
print('-' * 15)
